# **Data** **Creation** to store the student_marks_data
For students name - 1D array
for students subjects - 1D array
For students marks - 2D array (because one student has his marks in various subjects, need to store in table format so go for 2D) and (We can create a 2d array but in that what happens is as array stores homogenous elements in it, it will convert all datatypes to similar datatype having the highest priority so it is efficient go with this idea)

[7]


# **Data Creation**

In [17]:
import numpy as np

In [18]:
np.random.seed(42)
marks = np.random.randint(35, 101, size=(8, 5))
marks

array([[86, 49, 95, 55, 58],
       [37, 56, 87, 36, 64],
       [72, 36, 98, 94, 55],
       [67, 92, 56, 83, 93],
       [76, 94, 49, 96, 96],
       [81, 96, 85, 89, 98],
       [37, 85, 41, 55, 73],
       [52, 38, 94, 48, 43]])

# **Data Exploration**

In [19]:
marks.ndim

2

In [20]:
marks.size

40

In [21]:
marks.reshape
marks

array([[86, 49, 95, 55, 58],
       [37, 56, 87, 36, 64],
       [72, 36, 98, 94, 55],
       [67, 92, 56, 83, 93],
       [76, 94, 49, 96, 96],
       [81, 96, 85, 89, 98],
       [37, 85, 41, 55, 73],
       [52, 38, 94, 48, 43]])

In [22]:
marks.dtype

dtype('int64')

# **Data Transformation**

In [23]:
# Transpose to get subjects as rows
marks_T = marks.T
print("Transposed Marks:\n", marks_T)

# Flatten marks into 1D array
marks_flat = marks.flatten()
print("Flattened Marks:", marks_flat)


Transposed Marks:
 [[86 37 72 67 76 81 37 52]
 [49 56 36 92 94 96 85 38]
 [95 87 98 56 49 85 41 94]
 [55 36 94 83 96 89 55 48]
 [58 64 55 93 96 98 73 43]]
Flattened Marks: [86 49 95 55 58 37 56 87 36 64 72 36 98 94 55 67 92 56 83 93 76 94 49 96
 96 81 96 85 89 98 37 85 41 55 73 52 38 94 48 43]


# **Data Combination**

In [26]:
# Adding a new student
new_student_marks = np.array([[88, 82, 79, np.random.randint(35, 101), np.random.randint(35, 101)]]) # Added two more random values
marks_updated = np.vstack([marks, new_student_marks])
print("Marks after adding a new student:\n", marks_updated)

# Adding a new subject (column)
# new_subject_marks = np.array([[80], [90], [85], [75], [88]]) # Original new_subject_marks
new_subject_marks = np.random.randint(35, 101, size=(marks_updated.shape[0], 1)) # Generate random marks for the new subject with correct number of rows
marks_updated = np.hstack([marks_updated, new_subject_marks])
print("Marks after adding a new subject:\n", marks_updated)

Marks after adding a new student:
 [[86 49 95 55 58]
 [37 56 87 36 64]
 [72 36 98 94 55]
 [67 92 56 83 93]
 [76 94 49 96 96]
 [81 96 85 89 98]
 [37 85 41 55 73]
 [52 38 94 48 43]
 [88 82 79 87 36]]
Marks after adding a new subject:
 [[86 49 95 55 58 94]
 [37 56 87 36 64 78]
 [72 36 98 94 55 42]
 [67 92 56 83 93 81]
 [76 94 49 96 96 69]
 [81 96 85 89 98 70]
 [37 85 41 55 73 84]
 [52 38 94 48 43 38]
 [88 82 79 87 36 36]]


# **Data Modification**

In [27]:
# Update Alice's Math marks
marks_updated[0, 0] = 95

# Remove last subject
marks_without_last = np.delete(marks_updated, -1, axis=1)

# Unique marks
unique_marks = np.unique(marks_updated)
print("Unique Marks:", unique_marks)


Unique Marks: [36 37 38 41 42 43 48 49 52 55 56 58 64 67 69 70 72 73 76 78 79 81 82 83
 84 85 87 88 89 92 93 94 95 96 98]


# **Data Type Handling**

In [28]:
# Convert marks to float
marks_float = marks_updated.astype(float)
print("Marks as float:\n", marks_float)


Marks as float:
 [[95. 49. 95. 55. 58. 94.]
 [37. 56. 87. 36. 64. 78.]
 [72. 36. 98. 94. 55. 42.]
 [67. 92. 56. 83. 93. 81.]
 [76. 94. 49. 96. 96. 69.]
 [81. 96. 85. 89. 98. 70.]
 [37. 85. 41. 55. 73. 84.]
 [52. 38. 94. 48. 43. 38.]
 [88. 82. 79. 87. 36. 36.]]


# **COPY vs VIEW**

In [29]:
# View (changes affect original)
marks_view = marks_updated.view()
marks_view[0, 0] = 100
print("Original after view modification:\n", marks_updated)

# Copy (changes do NOT affect original)
marks_copy = marks_updated.copy()
marks_copy[0, 0] = 50
print("Original after copy modification:\n", marks_updated)


Original after view modification:
 [[100  49  95  55  58  94]
 [ 37  56  87  36  64  78]
 [ 72  36  98  94  55  42]
 [ 67  92  56  83  93  81]
 [ 76  94  49  96  96  69]
 [ 81  96  85  89  98  70]
 [ 37  85  41  55  73  84]
 [ 52  38  94  48  43  38]
 [ 88  82  79  87  36  36]]
Original after copy modification:
 [[100  49  95  55  58  94]
 [ 37  56  87  36  64  78]
 [ 72  36  98  94  55  42]
 [ 67  92  56  83  93  81]
 [ 76  94  49  96  96  69]
 [ 81  96  85  89  98  70]
 [ 37  85  41  55  73  84]
 [ 52  38  94  48  43  38]
 [ 88  82  79  87  36  36]]


## ✅ Summary of Concepts Covered:

1. Creating and exploring NumPy arrays

2. Reshaping, flattening, and transposing

3. Combining and splitting arrays

4. Updating and removing data

5. Handling different data types

6. Understanding views vs copies






