In [2]:
import numpy as np

class NumPyCalculator:
    def __init__(self, arr1, arr2=None):
        self.arr1 = np.array(arr1)
        if arr2 is not None:
            self.arr2 = np.array(arr2)
        else:
            self.arr2 = None

    # --- Arithmetic Operations ---
    def add(self):
        return self.arr1 + self.arr2

    def subtract(self):
        return self.arr1 - self.arr2

    def multiply(self):
        return self.arr1 * self.arr2

    def divide(self):
        return np.divide(self.arr1, self.arr2, out=np.zeros_like(self.arr1, dtype=float), where=self.arr2 != 0)

    def power(self):
        return np.power(self.arr1, self.arr2)

    # --- Statistical Operations ---
    def mean(self):
        return np.mean(self.arr1)

    def median(self):
        return np.median(self.arr1)

    def std_dev(self):
        return np.std(self.arr1)

    def variance(self):
        return np.var(self.arr1)

    def minimum(self):
        return np.min(self.arr1)

    def maximum(self):
        return np.max(self.arr1)

    def total_sum(self):
        return np.sum(self.arr1)

    def total_product(self):
        return np.prod(self.arr1)

    def get_shape(self):
        return self.arr1.shape

    def get_size(self):
        return self.arr1.size

    def get_dtype(self):
        return self.arr1.dtype

    # --- Array Manipulation ---
    def reshape(self, new_shape):
        try:
            return self.arr1.reshape(new_shape)
        except ValueError as e:
            return f"Error: {e}"

    def sort(self, reverse=False):
        if reverse:
            return np.sort(self.arr1)[::-1]
        else:
            return np.sort(self.arr1)

    def unique_values(self):
        return np.unique(self.arr1)

    def first_element(self):
        return self.arr1.flatten()[0]

    def last_element(self):
        return self.arr1.flatten()[-1]

    def filter_greater_than_mean(self):
        mean_val = self.mean()
        return self.arr1[self.arr1 > mean_val]


# --- Menu-driven Program ---
while True:
    print("\n===== NumPy Calculator =====")
    print("1. Arithmetic Operations")
    print("2. Statistical Operations")
    print("3. Array Manipulation")
    print("4. Exit")

    choice = input("Enter your choice (1-4): ").strip()

    # ---- ARITHMETIC OPERATIONS ----
    if choice == '1':
        try:
            arr1 = list(map(float, input("Enter first array elements separated by space: ").split()))
            arr2 = list(map(float, input("Enter second array elements separated by space: ").split()))
            calc = NumPyCalculator(arr1, arr2)

            print("\n--- Arithmetic Results ---")
            print("Addition:", calc.add())
            print("Subtraction:", calc.subtract())
            print("Multiplication:", calc.multiply())
            print("Division:", calc.divide())
            print("Power:", calc.power())

        except ValueError:
            print("❌ Invalid input! Please enter only numeric values separated by spaces.")

    # ---- STATISTICAL OPERATIONS ----
    elif choice == '2':
        try:
            arr1 = list(map(float, input("Enter array elements separated by space: ").split()))
            calc = NumPyCalculator(arr1)

            print("\n--- Statistical Results ---")
            print("Mean:", calc.mean())
            print("Median:", calc.median())
            print("Standard Deviation:", calc.std_dev())
            print("Variance:", calc.variance())
            print("Minimum:", calc.minimum())
            print("Maximum:", calc.maximum())
            print("Sum:", calc.total_sum())
            print("Product:", calc.total_product())
            print("Shape:", calc.get_shape())
            print("Size:", calc.get_size())
            print("Data Type:", calc.get_dtype())

        except ValueError:
            print("❌ Invalid input! Please enter only numeric values separated by spaces.")

    # ---- ARRAY MANIPULATION ----
    elif choice == '3':
        try:
            rows = int(input("Enter number of rows: ").strip())
            cols = int(input("Enter number of columns: ").strip())

            print(f"Enter {rows * cols} elements separated by space:")
            elements = list(map(float, input().split()))

            if len(elements) != rows * cols:
                print(f"❌ You must enter exactly {rows * cols} elements.")
                continue

            arr1 = np.array(elements).reshape(rows, cols)
            calc = NumPyCalculator(arr1)

            print("\n--- Array Manipulation ---")
            print("Original Array:\n", calc.arr1)
            print("Sorted:", calc.sort())
            print("Reverse Sorted:", calc.sort(reverse=True))
            print("Unique Values:", calc.unique_values())
            print("First Element:", calc.first_element())
            print("Last Element:", calc.last_element())
            print("Values greater than mean:", calc.filter_greater_than_mean())

            try:
                new_shape = tuple(map(int, input("Enter new shape (e.g., 3 2): ").split()))
                print("Reshaped Array:\n", calc.reshape(new_shape))
            except ValueError:
                print("❌ Invalid shape entered.")

        except ValueError:
            print("❌ Please enter valid numbers for rows, columns, and elements.")

    # ---- EXIT ----
    elif choice == '4':
        print("✅ Exiting program. Goodbye 👋")
        break

    else:
        print("❌ Invalid choice! Please enter a number between 1 and 4.")



===== NumPy Calculator =====
1. Arithmetic Operations
2. Statistical Operations
3. Array Manipulation
4. Exit

--- Arithmetic Results ---
Addition: [3. 5. 7. 9.]
Subtraction: [-1. -1. -1. -1.]
Multiplication: [ 2.  6. 12. 20.]
Division: [0.5        0.66666667 0.75       0.8       ]
Power: [1.000e+00 8.000e+00 8.100e+01 1.024e+03]

===== NumPy Calculator =====
1. Arithmetic Operations
2. Statistical Operations
3. Array Manipulation
4. Exit

--- Statistical Results ---
Mean: 4.0
Median: 4.0
Standard Deviation: 1.7728105208558367
Variance: 3.142857142857143
Minimum: 1.0
Maximum: 6.0
Sum: 28.0
Product: 5760.0
Shape: (7,)
Size: 7
Data Type: float64

===== NumPy Calculator =====
1. Arithmetic Operations
2. Statistical Operations
3. Array Manipulation
4. Exit
✅ Exiting program. Goodbye 👋


In [3]:
import numpy as np

# ======================================
#Input Function (Handles 1D & 2D Arrays)
# ======================================
def take_array(name):
    print(f"\n➡ Enter data for {name}:")
    array_type = int(input("Enter 1 for 1D array or 2 for 2D array: "))

    if array_type == 1:
        arr = np.array(list(map(float, input("Enter elements (space-separated): ").split())))
    else:
        rows = int(input("Enter number of rows: "))
        cols = int(input("Enter number of columns: "))
        print(f"Enter elements row by row for {name}:")
        data = []
        for i in range(rows):
            row = list(map(float, input(f"Row {i+1}: ").split()))
            data.append(row)
        arr = np.array(data)
    return arr


def arithmetic_operations(a, b):
    print("\n🧮 Basic Arithmetic Operations (using loops)")

    # Ensure same shape
    if a.shape != b.shape:
        print("⚠ Arrays must have the same shape for element-wise operations!")
        return

    # Perform manually with loops
    result_add = np.zeros_like(a)
    result_sub = np.zeros_like(a)
    result_mul = np.zeros_like(a)
    result_div = np.zeros_like(a)
    result_pow = np.zeros_like(a)

    # 1D arrays
    if a.ndim == 1:
        for i in range(len(a)):
            result_add[i] = a[i] + b[i]
            result_sub[i] = a[i] - b[i]
            result_mul[i] = a[i] * b[i]
            result_div[i] = a[i] / b[i]
            result_pow[i] = a[i] ** b[i]
    else:  # 2D arrays
        for i in range(a.shape[0]):
            for j in range(a.shape[1]):
                result_add[i][j] = a[i][j] + b[i][j]
                result_sub[i][j] = a[i][j] - b[i][j]
                result_mul[i][j] = a[i][j] * b[i][j]
                result_div[i][j] = a[i][j] / b[i][j]
                result_pow[i][j] = a[i][j] ** b[i][j]

    print("Addition:\n", result_add)
    print("Subtraction:\n", result_sub)
    print("Multiplication:\n", result_mul)
    print("Division:\n", result_div)
    print("Power (a^b):\n", result_pow)



def statistical_operations(a, b):
    print("\n📊 Statistical Operations")
    combined = np.concatenate((a.flatten(), b.flatten()))
    print("Mean:", np.mean(combined))
    print("Median:", np.median(combined))
    print("Standard Deviation:", np.std(combined))
    print("Variance:", np.var(combined))
    print("Minimum:", np.min(combined))
    print("Maximum:", np.max(combined))
    print("Sum:", np.sum(combined))
    print("Product:", np.prod(combined))
    print("Shape (Array A):", a.shape)
    print("Size (Array A):", a.size)
    print("Data Type:", a.dtype)


def array_manipulation(a, b):
    print("\n🔁 Array Manipulation")

    combined = np.concatenate((a.flatten(), b.flatten()))
    mean_val = np.mean(combined)

    # Reshape if possible
    try:
        reshaped = a.reshape(a.shape[::-1])
        print("Reshaped Array A:\n", reshaped)
    except ValueError:
        print("Cannot reshape array A (incompatible dimensions).")

    # Sorting using loop (manual bubble sort logic for small arrays)
    flat = combined.copy()
    for i in range(len(flat)):
        for j in range(i + 1, len(flat)):
            if flat[i] > flat[j]:
                flat[i], flat[j] = flat[j], flat[i]
    print("Sorted (Manual Bubble Sort):", flat)
    print("Reverse Sorted:", flat[::-1])

    # Unique values manually
    unique_values = []
    for val in flat:
        if val not in unique_values:
            unique_values.append(val)
    print("Unique Values (Manual):", unique_values)

    # First & last elements
    print("First Element of Array A:", a.flatten()[0])
    print("Last Element of Array A:", a.flatten()[-1])

    # Filtering values greater than mean (using loop)
    greater_than_mean = []
    for val in combined:
        if val > mean_val:
            greater_than_mean.append(val)
    print(f"Values greater than mean ({mean_val}):", greater_than_mean)




def main():
    print("🔢 NumPy Mathematical Calculator (1D / 2D + Functions + Loops) 🔢")

    arr1 = take_array("Array A")
    arr2 = take_array("Array B")

    print("\nArray A:\n", arr1)
    print("Array B:\n", arr2)

    arithmetic_operations(arr1, arr2)
    statistical_operations(arr1, arr2)
    array_manipulation(arr1, arr2)


if __name__ == "__main__":
    main()

🔢 NumPy Mathematical Calculator (1D / 2D + Functions + Loops) 🔢

➡ Enter data for Array A:

➡ Enter data for Array B:
Enter elements row by row for Array B:

Array A:
 [1. 2. 3. 4.]
Array B:
 [[1.]
 [2.]]

🧮 Basic Arithmetic Operations (using loops)
⚠ Arrays must have the same shape for element-wise operations!

📊 Statistical Operations
Mean: 2.1666666666666665
Median: 2.0
Standard Deviation: 1.0671873729054748
Variance: 1.1388888888888888
Minimum: 1.0
Maximum: 4.0
Sum: 13.0
Product: 48.0
Shape (Array A): (4,)
Size (Array A): 4
Data Type: float64

🔁 Array Manipulation
Reshaped Array A:
 [1. 2. 3. 4.]
Sorted (Manual Bubble Sort): [1. 1. 2. 2. 3. 4.]
Reverse Sorted: [4. 3. 2. 2. 1. 1.]
Unique Values (Manual): [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0)]
First Element of Array A: 1.0
Last Element of Array A: 4.0
Values greater than mean (2.1666666666666665): [np.float64(3.0), np.float64(4.0)]
